// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7bXdPVnDsIQt1nP5kelUKhcBYb445qf0',
    appId: '1:139194513211:web:617e0ce82d33a86123291e',
    messagingSenderId: '139194513211',
    projectId: 'insightlens-f1f6e',
    authDomain: 'insightlens-f1f6e.firebaseapp.com',
    storageBucket: 'insightlens-f1f6e.appspot.com',
    measurementId: 'G-RGF5EFVVX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOqSaxTlN6k-tRzp6IWDHURJ6u_MHaV1E',
    appId: '1:139194513211:android:7dd0a574a8db321e23291e',
    messagingSenderId: '139194513211',
    projectId: 'insightlens-f1f6e',
    storageBucket: 'insightlens-f1f6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtkcXWB2tZV9QcMAzVbdRB8khsBsSLydU',
    appId: '1:139194513211:ios:bd6c1ef35a09360223291e',
    messagingSenderId: '139194513211',
    projectId: 'insightlens-f1f6e',
    storageBucket: 'insightlens-f1f6e.appspot.com',
    iosBundleId: 'com.example.insightLens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtkcXWB2tZV9QcMAzVbdRB8khsBsSLydU',
    appId: '1:139194513211:ios:dae6601ce3a8a47f23291e',
    messagingSenderId: '139194513211',
    projectId: 'insightlens-f1f6e',
    storageBucket: 'insightlens-f1f6e.appspot.com',
    iosBundleId: 'com.example.insightLens.RunnerTests',
  );
}
