// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq3ubXDtgjvcL47ewBlCFPMksJ-w8ZRiw',
    appId: '1:136691009068:web:9010691607eeb0f58a7389',
    messagingSenderId: '136691009068',
    projectId: 'insightlens-25cb1',
    authDomain: 'insightlens-25cb1.firebaseapp.com',
    storageBucket: 'insightlens-25cb1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCysfuyKvcNK5Bh43P1U05-Ymp3JKJt7Zw',
    appId: '1:136691009068:android:2b8855a7e1e9c7eb8a7389',
    messagingSenderId: '136691009068',
    projectId: 'insightlens-25cb1',
    storageBucket: 'insightlens-25cb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS7NnVaDbc33PEVecIvhZFDwH0t1UhomQ',
    appId: '1:136691009068:ios:5985b7492cba45388a7389',
    messagingSenderId: '136691009068',
    projectId: 'insightlens-25cb1',
    storageBucket: 'insightlens-25cb1.appspot.com',
    iosBundleId: 'com.example.insightLens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS7NnVaDbc33PEVecIvhZFDwH0t1UhomQ',
    appId: '1:136691009068:ios:805e5d4eb33e2c488a7389',
    messagingSenderId: '136691009068',
    projectId: 'insightlens-25cb1',
    storageBucket: 'insightlens-25cb1.appspot.com',
    iosBundleId: 'com.example.insightLens.RunnerTests',
  );
}
